export interface CountryCodeData {
  Id: string;
  flag: string;
  code: string;
  name: string;
  phoneNumberLength: number;
}

export const COUNTRIES: CountryCodeData[] = [
  { Id: "1", flag: "at", code: "43", name: "Austria", phoneNumberLength: 10 },
  { Id: "2", flag: "af", code: "93", name: "Afghanistan", phoneNumberLength: 9 },
  { Id: "3", flag: "ag", code: "1", name: "Antigua and Barbuda", phoneNumberLength: 10 },
  { Id: "4", flag: "al", code: "355", name: "Albania", phoneNumberLength: 9 },
  { Id: "5", flag: "as", code: "1", name: "American Samoa", phoneNumberLength: 10 },
  { Id: "6", flag: "ad", code: "376", name: "Andorra", phoneNumberLength: 6 },
  { Id: "7", flag: "ao", code: "244", name: "Angola", phoneNumberLength: 9 },
  { Id: "8", flag: "am", code: "374", name: "Armenia", phoneNumberLength: 8 },
  { Id: "9", flag: "aw", code: "297", name: "Aruba", phoneNumberLength: 7 },
  { Id: "10", flag: "au", code: "61", name: "Australia", phoneNumberLength: 9 },
  { Id: "11", flag: "ai", code: "264", name: "Anguilla", phoneNumberLength: 7 },
  { Id: "12", flag: "az", code: "994", name: "Azerbaijan", phoneNumberLength: 9 },
  { Id: "13", flag: "be", code: "32", name: "Belgium", phoneNumberLength: 9 },
  { Id: "14", flag: "bd", code: "880", name: "Bangladesh", phoneNumberLength: 10 },
  { Id: "15", flag: "bb", code: "246", name: "Barbados", phoneNumberLength: 7 },
  { Id: "16", flag: "bj", code: "229", name: "Benin", phoneNumberLength: 8 },
  { Id: "17", flag: "bm", code: "441", name: "Bermuda", phoneNumberLength: 7 },
  { Id: "18", flag: "bf", code: "226", name: "Burkina Faso", phoneNumberLength: 8 },
  { Id: "19", flag: "bg", code: "359", name: "Bulgaria", phoneNumberLength: 9 },
  { Id: "20", flag: "bt", code: "975", name: "Bhutan", phoneNumberLength: 8 },
  { Id: "21", flag: "bi", code: "257", name: "Burundi", phoneNumberLength: 8 },
  { Id: "22", flag: "ba", code: "387", name: "Bosnia and Herzegovina", phoneNumberLength: 8 },
  { Id: "23", flag: "bo", code: "591", name: "Bolivia", phoneNumberLength: 8 },
  { Id: "24", flag: "br", code: "55", name: "Brazil", phoneNumberLength: 10 },
  { Id: "25", flag: "bh", code: "973", name: "Bahrain", phoneNumberLength: 8 },
  { Id: "26", flag: "bn", code: "673", name: "Brunei", phoneNumberLength: 7 },
  { Id: "27", flag: "bs", code: "242", name: "Bahamas", phoneNumberLength: 7 },
  { Id: "28", flag: "vg", code: "284", name: "British Virgin Islands", phoneNumberLength: 7 },
  { Id: "29", flag: "by", code: "375", name: "Belarus", phoneNumberLength: 9 },
  { Id: "30", flag: "bz", code: "501", name: "Belize", phoneNumberLength: 7 },
  { Id: "31", flag: "cu", code: "53", name: "Cuba", phoneNumberLength: 8 },
  { Id: "32", flag: "cm", code: "237", name: "Cameroon", phoneNumberLength: 8 },
  { Id: "33", flag: "ky", code: "345", name: "Cayman Islands", phoneNumberLength: 7 },
  { Id: "34", flag: "ca", code: "1", name: "Canada", phoneNumberLength: 10 },
  { Id: "35", flag: "ch", code: "41", name: "Switzerland", phoneNumberLength: 9 },
  { Id: "36", flag: "ci", code: "225", name: "Cote d'Ivoire", phoneNumberLength: 8 },
  { Id: "37", flag: "lk", code: "94", name: "Sri Lanka", phoneNumberLength: 10 },
  { Id: "38", flag: "co", code: "57", name: "Colombia", phoneNumberLength: 10 },
  { Id: "39", flag: "cc", code: "891", name: "Cocos Islands", phoneNumberLength: 9 },
  { Id: "40", flag: "km", code: "269", name: "Comoros", phoneNumberLength: 7 },
  { Id: "41", flag: "ck", code: "682", name: "Cook Islands", phoneNumberLength: 5 },
  { Id: "42", flag: "cr", code: "506", name: "Costa Rica", phoneNumberLength: 8 },
  { Id: "43", flag: "cv", code: "238", name: "Cape Verde", phoneNumberLength: 7 },
  { Id: "44", flag: "cy", code: "357", name: "Cyprus", phoneNumberLength: 8 },
  { Id: "45", flag: "cz", code: "420", name: "Czech Republic", phoneNumberLength: 9 },
  { Id: "46", flag: "de", code: "49", name: "Germany", phoneNumberLength: 10 },
  { Id: "47", flag: "dj", code: "253", name: "Djibouti", phoneNumberLength: 8 },
  { Id: "48", flag: "dk", code: "45", name: "Denmark", phoneNumberLength: 8 },
  { Id: "49", flag: "do", code: "1", name: "Dominican Republic", phoneNumberLength: 10 },
  { Id: "50", flag: "dz", code: "213", name: "Algeria", phoneNumberLength: 9 },
  { Id: "51", flag: "es", code: "34", name: "Spain", phoneNumberLength: 9 },
  { Id: "52", flag: "ke", code: "254", name: "Kenya", phoneNumberLength: 9 },
  { Id: "53", flag: "tz", code: "255", name: "Tanzania", phoneNumberLength: 9 },
  { Id: "54", flag: "ug", code: "256", name: "Uganda", phoneNumberLength: 9 },
  { Id: "55", flag: "ec", code: "593", name: "Ecuador", phoneNumberLength: 9 },
  { Id: "56", flag: "er", code: "291", name: "Eritrea", phoneNumberLength: 7 },
  { Id: "57", flag: "sv", code: "503", name: "El Salvador", phoneNumberLength: 8 },
  { Id: "58", flag: "eg", code: "20", name: "Egypt", phoneNumberLength: 10 },
  { Id: "59", flag: "et", code: "251", name: "Ethiopia", phoneNumberLength: 9 },
  { Id: "60", flag: "ee", code: "372", name: "Estonia", phoneNumberLength: 7 },
  { Id: "61", flag: "fr", code: "33", name: "France", phoneNumberLength: 9 },
  { Id: "62", flag: "fk", code: "500", name: "Falkland Islands", phoneNumberLength: 5 },
  { Id: "63", flag: "fo", code: "298", name: "Faroe Islands", phoneNumberLength: 6 },
  { Id: "64", flag: "gf", code: "594", name: "French Guiana", phoneNumberLength: 9 },
  { Id: "65", flag: "fj", code: "679", name: "Fiji", phoneNumberLength: 7 },
  { Id: "66", flag: "li", code: "423", name: "Liechtenstein", phoneNumberLength: 7 },
  { Id: "67", flag: "pf", code: "689", name: "French Polynesia", phoneNumberLength: 6 },
  { Id: "68", flag: "fm", code: "691", name: "Micronesia", phoneNumberLength: 7 },
  { Id: "69", flag: "ga", code: "241", name: "Gabon", phoneNumberLength: 7 },
  { Id: "70", flag: "gs", code: "970", name: "Gaza Strip", phoneNumberLength: 8 },
  { Id: "71", flag: "gb", code: "44", name: "United Kingdom", phoneNumberLength: 10 },
  { Id: "72", flag: "gg", code: "44", name: "Guernsey", phoneNumberLength: 10 },
  { Id: "73", flag: "je", code: "44", name: "Jersey", phoneNumberLength: 10 },
  { Id: "74", flag: "im", code: "44", name: "Isle of Man", phoneNumberLength: 10 },
  { Id: "75", flag: "gi", code: "350", name: "Gibraltar", phoneNumberLength: 8 },
  { Id: "76", flag: "gt", code: "502", name: "Guatemala", phoneNumberLength: 8 },
  { Id: "77", flag: "ge", code: "995", name: "Georgia", phoneNumberLength: 9 },
  { Id: "78", flag: "gh", code: "233", name: "Ghana", phoneNumberLength: 9 },
  { Id: "79", flag: "gw", code: "245", name: "Guinea-Bissau", phoneNumberLength: 7 },
  { Id: "80", flag: "gq", code: "240", name: "Equatorial Guinea", phoneNumberLength: 9 },
  { Id: "81", flag: "gr", code: "30", name: "Greece", phoneNumberLength: 10 },
  { Id: "82", flag: "gl", code: "299", name: "Greenland", phoneNumberLength: 6 },
  { Id: "83", flag: "gp", code: "590", name: "Guadeloupe", phoneNumberLength: 9 },
  { Id: "84", flag: "gu", code: "1", name: "Guam", phoneNumberLength: 10 },
  { Id: "85", flag: "gy", code: "592", name: "Guyana", phoneNumberLength: 7 },
  { Id: "86", flag: "hu", code: "36", name: "Hungary", phoneNumberLength: 9 },
  { Id: "87", flag: "hn", code: "504", name: "Honduras", phoneNumberLength: 8 },
  { Id: "88", flag: "sh", code: "290", name: "Saint Helena", phoneNumberLength: 4 },
  { Id: "89", flag: "hk", code: "852", name: "Hong Kong", phoneNumberLength: 8 },
  { Id: "90", flag: "hr", code: "385", name: "Croatia", phoneNumberLength: 9 },
  { Id: "91", flag: "it", code: "39", name: "Italy", phoneNumberLength: 10 },
  { Id: "92", flag: "il", code: "972", name: "Israel", phoneNumberLength: 9 },
  { Id: "93", flag: "in", code: "91", name: "India", phoneNumberLength: 10 },
  { Id: "94", flag: "ir", code: "98", name: "Iran", phoneNumberLength: 10 },
  { Id: "95", flag: "ie", code: "353", name: "Ireland", phoneNumberLength: 9 },
  { Id: "96", flag: "iq", code: "964", name: "Iraq", phoneNumberLength: 10 },
  { Id: "97", flag: "is", code: "354", name: "Iceland", phoneNumberLength: 7 },
  { Id: "98", flag: "jp", code: "81", name: "Japan", phoneNumberLength: 10 },
  { Id: "99", flag: "jm", code: "876", name: "Jamaica", phoneNumberLength: 7 },
  { Id: "100", flag: "jo", code: "962", name: "Jordan", phoneNumberLength: 9 },
  { Id: "101", flag: "kh", code: "855", name: "Cambodia", phoneNumberLength: 9 },
  { Id: "102", flag: "kz", code: "7", name: "Kazakhstan", phoneNumberLength: 10 },
  { Id: "103", flag: "kg", code: "996", name: "Kyrgyzstan", phoneNumberLength: 9 },
  { Id: "104", flag: "ki", code: "686", name: "Kiribati", phoneNumberLength: 5 },
  { Id: "105", flag: "kn", code: "869", name: "Saint Kitts and Nevis", phoneNumberLength: 7 },
  { Id: "106", flag: "kv", code: "383", name: "Kosovo", phoneNumberLength: 8 },
  { Id: "107", flag: "kw", code: "965", name: "Kuwait", phoneNumberLength: 8 },
  { Id: "108", flag: "lu", code: "352", name: "Luxembourg", phoneNumberLength: 9 },
  { Id: "109", flag: "la", code: "856", name: "Laos", phoneNumberLength: 8 },
  { Id: "110", flag: "ly", code: "218", name: "Libya", phoneNumberLength: 9 },
  { Id: "111", flag: "lr", code: "231", name: "Liberia", phoneNumberLength: 7 },
  { Id: "112", flag: "ls", code: "266", name: "Lesotho", phoneNumberLength: 8 },
  { Id: "113", flag: "lt", code: "370", name: "Lithuania", phoneNumberLength: 8 },
  { Id: "114", flag: "lv", code: "371", name: "Latvia", phoneNumberLength: 8 },
  { Id: "115", flag: "mt", code: "356", name: "Malta", phoneNumberLength: 8 },
  { Id: "116", flag: "ma", code: "212", name: "Morocco", phoneNumberLength: 9 },
  { Id: "117", flag: "mo", code: "853", name: "Macau", phoneNumberLength: 8 },
  { Id: "118", flag: "my", code: "60", name: "Malaysia", phoneNumberLength: 9 },
  { Id: "119", flag: "mq", code: "596", name: "Martinique", phoneNumberLength: 9 },
  { Id: "120", flag: "yt", code: "262", name: "Mayotte", phoneNumberLength: 9 },
  { Id: "121", flag: "mc", code: "377", name: "Monaco", phoneNumberLength: 8 },
  { Id: "122", flag: "md", code: "373", name: "Moldova", phoneNumberLength: 8 },
  { Id: "123", flag: "mx", code: "52", name: "Mexico", phoneNumberLength: 10 },
  { Id: "124", flag: "mh", code: "692", name: "Marshall Islands", phoneNumberLength: 7 },
  { Id: "125", flag: "mk", code: "389", name: "Macedonia", phoneNumberLength: 8 },
  { Id: "126", flag: "me", code: "382", name: "Montenegro", phoneNumberLength: 8 },
  { Id: "127", flag: "mn", code: "976", name: "Mongolia", phoneNumberLength: 8 },
  { Id: "128", flag: "ms", code: "664", name: "Montserrat", phoneNumberLength: 7 },
  { Id: "129", flag: "mz", code: "258", name: "Mozambique", phoneNumberLength: 9 },
  { Id: "130", flag: "mu", code: "230", name: "Mauritius", phoneNumberLength: 7 },
  { Id: "131", flag: "mv", code: "960", name: "Maldives", phoneNumberLength: 7 },
  { Id: "132", flag: "mw", code: "265", name: "Malawi", phoneNumberLength: 7 },
  { Id: "133", flag: "mm", code: "95", name: "Myanmar", phoneNumberLength: 8 },
  { Id: "134", flag: "no", code: "47", name: "Norway", phoneNumberLength: 8 },
  { Id: "135", flag: "nl", code: "599", name: "Netherlands Antilles", phoneNumberLength: 7 },
  { Id: "136", flag: "na", code: "264", name: "Namibia", phoneNumberLength: 9 },
  { Id: "137", flag: "nr", code: "674", name: "Nauru", phoneNumberLength: 7 },
  { Id: "138", flag: "nc", code: "687", name: "New Caledonia", phoneNumberLength: 6 },
  { Id: "139", flag: "np", code: "977", name: "Nepal", phoneNumberLength: 10 },
  { Id: "140", flag: "ni", code: "505", name: "Nicaragua", phoneNumberLength: 8 },
  { Id: "141", flag: "nu", code: "683", name: "Niue", phoneNumberLength: 4 },
  { Id: "142", flag: "nl", code: "31", name: "Netherlands", phoneNumberLength: 9 },
  { Id: "143", flag: "mp", code: "1", name: "Northern Mariana Islands", phoneNumberLength: 10 },
  { Id: "144", flag: "kp", code: "850", name: "North Korea", phoneNumberLength: 8 },
  { Id: "145", flag: "nf", code: "672", name: "Norfolk Island", phoneNumberLength: 5 },
  { Id: "146", flag: "nz", code: "64", name: "New Zealand", phoneNumberLength: 9 },
  { Id: "147", flag: "om", code: "968", name: "Oman", phoneNumberLength: 8 },
  { Id: "148", flag: "pt", code: "351", name: "Portugal", phoneNumberLength: 9 },
  { Id: "149", flag: "pa", code: "507", name: "Panama", phoneNumberLength: 8 },
  { Id: "150", flag: "pw", code: "680", name: "Palau", phoneNumberLength: 7 },
  { Id: "151", flag: "pe", code: "51", name: "Peru", phoneNumberLength: 9 },
  { Id: "152", flag: "pn", code: "64", name: "Pitcairn Islands", phoneNumberLength: 5 },
  { Id: "153", flag: "pk", code: "92", name: "Pakistan", phoneNumberLength: 10 },
  { Id: "154", flag: "pl", code: "48", name: "Poland", phoneNumberLength: 9 },
  { Id: "155", flag: "pg", code: "675", name: "Papua New Guinea", phoneNumberLength: 7 },
  { Id: "156", flag: "pr", code: "1", name: "Puerto Rico", phoneNumberLength: 10 },
  { Id: "157", flag: "py", code: "595", name: "Paraguay", phoneNumberLength: 9 },
  { Id: "158", flag: "qa", code: "974", name: "Qatar", phoneNumberLength: 8 },
  { Id: "159", flag: "ru", code: "7", name: "Russia", phoneNumberLength: 10 },
  { Id: "160", flag: "ar", code: "54", name: "Argentina", phoneNumberLength: 10 },
  { Id: "161", flag: "bw", code: "267", name: "Botswana", phoneNumberLength: 7 },
  { Id: "162", flag: "tw", code: "886", name: "Taiwan", phoneNumberLength: 9 },
  { Id: "163", flag: "cf", code: "236", name: "Central African Republic", phoneNumberLength: 8 },
  { Id: "164", flag: "cd", code: "243", name: "Republic of the Congo", phoneNumberLength: 9 },
  { Id: "165", flag: "cl", code: "56", name: "Chile", phoneNumberLength: 9 },
  { Id: "166", flag: "re", code: "262", name: "Reunion", phoneNumberLength: 9 },
  { Id: "167", flag: "gn", code: "224", name: "Guinea", phoneNumberLength: 8 },
  { Id: "168", flag: "ht", code: "509", name: "Haiti", phoneNumberLength: 8 },
  { Id: "169", flag: "id", code: "62", name: "Indonesia", phoneNumberLength: 10 },
  { Id: "170", flag: "mr", code: "222", name: "Mauritania", phoneNumberLength: 8 },
  { Id: "171", flag: "lb", code: "961", name: "Lebanon", phoneNumberLength: 8 },
  { Id: "172", flag: "mg", code: "261", name: "Madagascar", phoneNumberLength: 9 },
  { Id: "173", flag: "ml", code: "223", name: "Mali", phoneNumberLength: 8 },
  { Id: "174", flag: "ne", code: "227", name: "Niger", phoneNumberLength: 8 },
  { Id: "175", flag: "ro", code: "40", name: "Romania", phoneNumberLength: 9 },
  { Id: "176", flag: "kr", code: "82", name: "South Korea", phoneNumberLength: 10 },
  { Id: "177", flag: "uy", code: "598", name: "Uruguay", phoneNumberLength: 8 },
  { Id: "178", flag: "ph", code: "63", name: "Philippines", phoneNumberLength: 10 },
  { Id: "179", flag: "za", code: "27", name: "South Africa", phoneNumberLength: 9 },
  { Id: "180", flag: "sm", code: "378", name: "San Marino", phoneNumberLength: 10 },
  { Id: "181", flag: "tg", code: "228", name: "Togo", phoneNumberLength: 8 },
  { Id: "182", flag: "rw", code: "250", name: "Rwanda", phoneNumberLength: 9 },
  { Id: "183", flag: "se", code: "46", name: "Sweden", phoneNumberLength: 9 },
  { Id: "184", flag: "sa", code: "966", name: "Saudi Arabia", phoneNumberLength: 9 },
  { Id: "185", flag: "sz", code: "268", name: "Swaziland", phoneNumberLength: 8 },
  { Id: "186", flag: "fi", code: "358", name: "Finland", phoneNumberLength: 10 },
  { Id: "187", flag: "sg", code: "65", name: "Singapore", phoneNumberLength: 8 },
  { Id: "188", flag: "sk", code: "421", name: "Slovakia", phoneNumberLength: 9 },
  { Id: "189", flag: "sb", code: "677", name: "Solomon Islands", phoneNumberLength: 7 },
  { Id: "190", flag: "si", code: "386", name: "Slovenia", phoneNumberLength: 8 },
  { Id: "191", flag: "mf", code: "1", name: "Saint Martin", phoneNumberLength: 10 },
  { Id: "192", flag: "sr", code: "597", name: "Suriname", phoneNumberLength: 7 },
  { Id: "193", flag: "sn", code: "221", name: "Senegal", phoneNumberLength: 9 },
  { Id: "194", flag: "so", code: "252", name: "Somalia", phoneNumberLength: 8 },
  { Id: "195", flag: "pm", code: "508", name: "Saint Pierre and Miquelon", phoneNumberLength: 6 },
  { Id: "196", flag: "rs", code: "381", name: "Serbia", phoneNumberLength: 9 },
  { Id: "197", flag: "st", code: "239", name: "Sao Tome and Principe", phoneNumberLength: 7 },
  { Id: "198", flag: "sd", code: "249", name: "Sudan", phoneNumberLength: 9 },
  { Id: "199", flag: "sj", code: "47", name: "Svalbard", phoneNumberLength: 8 },
  { Id: "200", flag: "sc", code: "248", name: "Seychelles", phoneNumberLength: 7 },
  { Id: "201", flag: "sy", code: "963", name: "Syria", phoneNumberLength: 9 },
  { Id: "202", flag: "tj", code: "992", name: "Tajikistan", phoneNumberLength: 9 },
  { Id: "203", flag: "td", code: "235", name: "Chad", phoneNumberLength: 8 },
  { Id: "204", flag: "th", code: "66", name: "Thailand", phoneNumberLength: 9 },
  { Id: "205", flag: "cn", code: "86", name: "China", phoneNumberLength: 11 },
  { Id: "206", flag: "tl", code: "670", name: "Timor-Leste", phoneNumberLength: 7 },
  { Id: "207", flag: "tm", code: "993", name: "Turkmenistan", phoneNumberLength: 8 },
  { Id: "208", flag: "tn", code: "216", name: "Tunisia", phoneNumberLength: 8 },
  { Id: "209", flag: "to", code: "676", name: "Tonga", phoneNumberLength: 5 },
  { Id: "210", flag: "tr", code: "90", name: "Turkey", phoneNumberLength: 10 },
  { Id: "211", flag: "tt", code: "868", name: "Trinidad and Tobago", phoneNumberLength: 7 },
  { Id: "212", flag: "tc", code: "1", name: "Turks and Caicos Islands", phoneNumberLength: 10 },
  { Id: "213", flag: "tv", code: "688", name: "Tuvalu", phoneNumberLength: 5 },
  { Id: "214", flag: "ua", code: "380", name: "Ukraine", phoneNumberLength: 9 },
  { Id: "215", flag: "ae", code: "971", name: "United Arab Emirates", phoneNumberLength: 9 },
  { Id: "216", flag: "us", code: "1", name: "USA", phoneNumberLength: 10 },
  { Id: "217", flag: "uz", code: "998", name: "Uzbekistan", phoneNumberLength: 9 },
  { Id: "218", flag: "va", code: "379", name: "Holy See", phoneNumberLength: 10 },
  { Id: "219", flag: "vi", code: "1", name: "U.S. Virgin Islands", phoneNumberLength: 10 },
  { Id: "220", flag: "vn", code: "84", name: "Vietnam", phoneNumberLength: 9 },
  { Id: "221", flag: "vu", code: "678", name: "Vanuatu", phoneNumberLength: 7 },
  { Id: "222", flag: "wf", code: "681", name: "Wallis and Futuna", phoneNumberLength: 6 },
  { Id: "223", flag: "gm", code: "220", name: "Gambia", phoneNumberLength: 7 },
  { Id: "224", flag: "sl", code: "232", name: "Sierra Leone", phoneNumberLength: 8 },
  { Id: "225", flag: "ng", code: "234", name: "Nigeria", phoneNumberLength: 10 },
  { Id: "226", flag: "dm", code: "767", name: "Dominica", phoneNumberLength: 7 },
  { Id: "227", flag: "ps", code: "970", name: "West Bank", phoneNumberLength: 8 },
  { Id: "228", flag: "gd", code: "473", name: "Grenada", phoneNumberLength: 7 },
  { Id: "229", flag: "lc", code: "758", name: "Saint Lucia", phoneNumberLength: 7 },
  { Id: "230", flag: "ws", code: "685", name: "Samoa", phoneNumberLength: 7 },
  { Id: "231", flag: "eh", code: "212", name: "Western Sahara", phoneNumberLength: 9 },
  { Id: "232", flag: "vc", code: "784", name: "Saint Vincent and the Grenadines", phoneNumberLength: 7 },
  { Id: "233", flag: "cx", code: "61", name: "Christmas Island", phoneNumberLength: 9 },
  { Id: "234", flag: "ye", code: "967", name: "Yemen", phoneNumberLength: 9 },
  { Id: "235", flag: "ve", code: "58", name: "Venezuela", phoneNumberLength: 10 },
  { Id: "236", flag: "zm", code: "260", name: "Zambia", phoneNumberLength: 9 },
  { Id: "237", flag: "zr", code: "243", name: "Zaire", phoneNumberLength: 9 },
  { Id: "238", flag: "zw", code: "263", name: "Zimbabwe", phoneNumberLength: 9 }
];
