import { SettingsPageConfig } from './settings-page.types';

export const SETTINGS_PAGE_CONFIGS: Record<string, SettingsPageConfig> = {
  attendanceRegularization: {
    storageKey: 'hrms_setting_regularization',
    title: 'Regularization Rules',
    kicker: 'Attendance Settings',
    description: 'Define attendance correction windows, approval rules, and supporting notes for late or missed punches.',
    itemName: 'regularization rule',
    emptyState: 'No regularization rules configured yet.',
    primaryMetricLabel: 'Approval rules',
    fields: [
      { key: 'name', label: 'Rule Name', type: 'text', required: true, placeholder: 'Standard punch correction' },
      { key: 'windowDays', label: 'Window (days)', type: 'number', required: true, placeholder: '3' },
      { key: 'approvalFlow', label: 'Approval Flow', type: 'select', required: true, options: [{ label: 'Manager', value: 'Manager' }, { label: 'HR', value: 'HR' }, { label: 'Manager + HR', value: 'Manager + HR' }] },
      { key: 'reasonRequired', label: 'Reason Required', type: 'toggle' },
      { key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Add operational instructions' },
    ],
    seedItems: [{ id: 'reg-1', name: 'Default Regularization', windowDays: 3, approvalFlow: 'Manager', reasonRequired: true, notes: 'Allow corrections for missed punch requests.' }],
  },
  attendanceMode: {
    storageKey: 'hrms_setting_attendance_mode',
    title: 'Attendance Modes',
    kicker: 'Attendance Settings',
    description: 'Manage the attendance channels available to employees such as mobile, kiosk, geo-fence, and biometric flows.',
    itemName: 'attendance mode',
    emptyState: 'No attendance modes configured yet.',
    primaryMetricLabel: 'Live modes',
    fields: [
      { key: 'name', label: 'Mode Name', type: 'text', required: true, placeholder: 'Mobile punch' },
      { key: 'channel', label: 'Channel', type: 'select', required: true, options: [{ label: 'Mobile', value: 'Mobile' }, { label: 'Web', value: 'Web' }, { label: 'Kiosk', value: 'Kiosk' }, { label: 'Biometric', value: 'Biometric' }] },
      { key: 'restricted', label: 'Restricted Mode', type: 'toggle' },
      { key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Mention who can use this mode' },
    ],
    seedItems: [{ id: 'mode-1', name: 'Mobile Punch', channel: 'Mobile', restricted: false, notes: 'Primary self-service mode for employees.' }],
  },
  kioskManager: {
    storageKey: 'hrms_setting_kiosk_manager',
    title: 'Kiosk Manager',
    kicker: 'Attendance Settings',
    description: 'Track kiosk admins, assigned sites, and the operational state of attendance kiosks.',
    itemName: 'kiosk admin',
    emptyState: 'No kiosk managers configured yet.',
    primaryMetricLabel: 'Kiosk admins',
    fields: [
      { key: 'name', label: 'Admin Name', type: 'text', required: true, placeholder: 'Front Desk Admin' },
      { key: 'location', label: 'Location', type: 'text', required: true, placeholder: 'HQ Reception' },
      { key: 'contact', label: 'Contact', type: 'text', placeholder: 'admin@company.com' },
      { key: 'active', label: 'Active', type: 'toggle' },
    ],
    seedItems: [{ id: 'kiosk-manager-1', name: 'Reception Admin', location: 'HQ Reception', contact: 'reception@company.com', active: true }],
  },
  kioskSetup: {
    storageKey: 'hrms_setting_kiosk_setup',
    title: 'Kiosk Setup',
    kicker: 'Attendance Settings',
    description: 'Define kiosk stations, device tags, and setup notes for shared attendance terminals.',
    itemName: 'kiosk station',
    emptyState: 'No kiosk stations configured yet.',
    primaryMetricLabel: 'Stations',
    fields: [
      { key: 'name', label: 'Station Name', type: 'text', required: true, placeholder: 'Main Gate Kiosk' },
      { key: 'deviceCode', label: 'Device Code', type: 'text', required: true, placeholder: 'KSK-001' },
      { key: 'location', label: 'Location', type: 'text', placeholder: 'Entry lobby' },
      { key: 'active', label: 'Active', type: 'toggle' },
    ],
    seedItems: [{ id: 'kiosk-1', name: 'Main Gate Kiosk', deviceCode: 'KSK-001', location: 'Entry lobby', active: true }],
  },
  deviceRestriction: {
    storageKey: 'hrms_setting_device_restriction',
    title: 'Device Restrictions',
    kicker: 'Attendance Settings',
    description: 'Register allowed devices, browser policies, and device-specific attendance restrictions.',
    itemName: 'device policy',
    emptyState: 'No device restrictions configured yet.',
    primaryMetricLabel: 'Allowed devices',
    fields: [
      { key: 'name', label: 'Policy Name', type: 'text', required: true, placeholder: 'Managed Android devices' },
      { key: 'deviceType', label: 'Device Type', type: 'select', required: true, options: [{ label: 'Android', value: 'Android' }, { label: 'iOS', value: 'iOS' }, { label: 'Desktop', value: 'Desktop' }] },
      { key: 'locked', label: 'Require Device Approval', type: 'toggle' },
      { key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Explain enforcement rules' },
    ],
    seedItems: [{ id: 'device-1', name: 'Managed Android Devices', deviceType: 'Android', locked: true, notes: 'Only approved devices can punch attendance.' }],
  },
  advanceAttendance: {
    storageKey: 'hrms_setting_advance_attendance',
    title: 'Advance Attendance Rules',
    kicker: 'Attendance Settings',
    description: 'Configure grace logic, overtime treatment, and edge-case rules that shape attendance calculations.',
    itemName: 'attendance rule',
    emptyState: 'No advanced attendance rules configured yet.',
    primaryMetricLabel: 'Rule blocks',
    fields: [
      { key: 'name', label: 'Rule Name', type: 'text', required: true, placeholder: 'Grace and overtime' },
      { key: 'threshold', label: 'Threshold', type: 'number', required: true, placeholder: '15' },
      { key: 'unit', label: 'Unit', type: 'select', required: true, options: [{ label: 'Minutes', value: 'Minutes' }, { label: 'Hours', value: 'Hours' }] },
      { key: 'enabled', label: 'Enabled', type: 'toggle' },
      { key: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Describe how the rule should work' },
    ],
    seedItems: [{ id: 'adv-1', name: 'Late Grace Window', threshold: 15, unit: 'Minutes', enabled: true, notes: 'Mark late after 15 minutes from shift start.' }],
  },
  flexiHoliday: {
    storageKey: 'hrms_setting_flexi_holiday',
    title: 'Flexi Holiday Plans',
    kicker: 'Attendance Settings',
    description: 'Maintain optional holiday plans and define which employees or teams can opt into them.',
    itemName: 'flexi holiday plan',
    emptyState: 'No flexi holiday plans configured yet.',
    primaryMetricLabel: 'Holiday plans',
    fields: [
      { key: 'name', label: 'Plan Name', type: 'text', required: true, placeholder: 'Regional flexi holidays' },
      { key: 'allowance', label: 'Allowance', type: 'number', required: true, placeholder: '2' },
      { key: 'eligibility', label: 'Eligibility', type: 'text', placeholder: 'All employees' },
      { key: 'active', label: 'Active', type: 'toggle' },
    ],
    seedItems: [{ id: 'flexi-1', name: 'Regional Flexi Plan', allowance: 2, eligibility: 'All employees', active: true }],
  },
  penalty: {
    storageKey: 'hrms_setting_penalty',
    title: 'Penalty Policies',
    kicker: 'Organisation Settings',
    description: 'Define penalties linked to attendance or operational discipline for internal visibility and governance.',
    itemName: 'penalty policy',
    emptyState: 'No penalty policies configured yet.',
    primaryMetricLabel: 'Penalty rules',
    fields: [
      { key: 'name', label: 'Policy Name', type: 'text', required: true, placeholder: 'Late arrival deduction' },
      { key: 'amount', label: 'Amount / Value', type: 'number', required: true, placeholder: '500' },
      { key: 'unit', label: 'Unit', type: 'select', required: true, options: [{ label: 'INR', value: 'INR' }, { label: 'Days', value: 'Days' }, { label: 'Points', value: 'Points' }] },
      { key: 'active', label: 'Active', type: 'toggle' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
    seedItems: [{ id: 'penalty-1', name: 'Late Arrival Deduction', amount: 500, unit: 'INR', active: true, notes: 'Applicable after repeated late arrivals.' }],
  },
  hierarchy: {
    storageKey: 'hrms_setting_hierarchy',
    title: 'Designation Hierarchy',
    kicker: 'Organisation Settings',
    description: 'Maintain reporting levels and role ladders so org structure stays visible across employees and approvals.',
    itemName: 'hierarchy level',
    emptyState: 'No hierarchy levels configured yet.',
    primaryMetricLabel: 'Hierarchy levels',
    fields: [
      { key: 'name', label: 'Level Name', type: 'text', required: true, placeholder: 'Team Lead' },
      { key: 'level', label: 'Level Order', type: 'number', required: true, placeholder: '3' },
      { key: 'reportsTo', label: 'Reports To', type: 'text', placeholder: 'Manager' },
      { key: 'active', label: 'Active', type: 'toggle' },
    ],
    seedItems: [{ id: 'hierarchy-1', name: 'Team Lead', level: 3, reportsTo: 'Manager', active: true }],
  },
  divisions: {
    storageKey: 'hrms_setting_divisions',
    title: 'Divisions',
    kicker: 'Organisation Settings',
    description: 'Create higher-order business divisions that group departments or business units together.',
    itemName: 'division',
    emptyState: 'No divisions configured yet.',
    primaryMetricLabel: 'Divisions',
    fields: [
      { key: 'name', label: 'Division Name', type: 'text', required: true, placeholder: 'North Region' },
      { key: 'head', label: 'Division Head', type: 'text', placeholder: 'Regional Director' },
      { key: 'active', label: 'Active', type: 'toggle' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
    seedItems: [{ id: 'division-1', name: 'Corporate Services', head: 'Operations Director', active: true, notes: 'Covers HR, Finance, and Admin support.' }],
  },
  policies: {
    storageKey: 'hrms_setting_policies',
    title: 'Policy Library',
    kicker: 'Organisation Settings',
    description: 'Maintain company policies, handbook references, and publication status from one place.',
    itemName: 'policy',
    emptyState: 'No policies configured yet.',
    primaryMetricLabel: 'Published policies',
    fields: [
      { key: 'name', label: 'Policy Name', type: 'text', required: true, placeholder: 'Work From Home Policy' },
      { key: 'owner', label: 'Owner', type: 'text', placeholder: 'HR Team' },
      { key: 'published', label: 'Published', type: 'toggle' },
      { key: 'summary', label: 'Summary', type: 'textarea', placeholder: 'Add a short overview of the policy' },
    ],
    seedItems: [{ id: 'policy-1', name: 'Work From Home Policy', owner: 'HR Team', published: true, summary: 'Defines eligibility and expectations for remote work.' }],
  },
  shortDayLeave: {
    storageKey: 'hrms_setting_short_day_leave',
    title: 'Short Day Leave Settings',
    kicker: 'Leave Settings',
    description: 'Control short-day requests, duration caps, and approval guidance for partial-day leave usage.',
    itemName: 'short day rule',
    emptyState: 'No short day leave rules configured yet.',
    primaryMetricLabel: 'Short day rules',
    fields: [
      { key: 'name', label: 'Rule Name', type: 'text', required: true, placeholder: 'Half-day request' },
      { key: 'hours', label: 'Allowed Hours', type: 'number', required: true, placeholder: '4' },
      { key: 'approvalFlow', label: 'Approval Flow', type: 'text', placeholder: 'Manager approval' },
      { key: 'active', label: 'Active', type: 'toggle' },
    ],
    seedItems: [{ id: 'short-day-1', name: 'Half-Day Request', hours: 4, approvalFlow: 'Manager approval', active: true }],
  },
  timeOff: {
    storageKey: 'hrms_setting_time_off',
    title: 'Time Off Settings',
    kicker: 'Leave Settings',
    description: 'Configure time-off allowances and request notes for hourly or partial absence workflows.',
    itemName: 'time off plan',
    emptyState: 'No time off settings configured yet.',
    primaryMetricLabel: 'Time off plans',
    fields: [
      { key: 'name', label: 'Plan Name', type: 'text', required: true, placeholder: 'Hourly time off' },
      { key: 'limit', label: 'Monthly Limit', type: 'number', required: true, placeholder: '8' },
      { key: 'unit', label: 'Unit', type: 'select', required: true, options: [{ label: 'Hours', value: 'Hours' }, { label: 'Requests', value: 'Requests' }] },
      { key: 'active', label: 'Active', type: 'toggle' },
    ],
    seedItems: [{ id: 'timeoff-1', name: 'Hourly Time Off', limit: 8, unit: 'Hours', active: true }],
  },
  compOff: {
    storageKey: 'hrms_setting_comp_off',
    title: 'Comp Off Settings',
    kicker: 'Leave Settings',
    description: 'Define compensatory off rules, expiry windows, and validation notes for overtime-linked leave.',
    itemName: 'comp off rule',
    emptyState: 'No comp off rules configured yet.',
    primaryMetricLabel: 'Comp off rules',
    fields: [
      { key: 'name', label: 'Rule Name', type: 'text', required: true, placeholder: 'Weekend overtime comp off' },
      { key: 'expiryDays', label: 'Expiry (days)', type: 'number', required: true, placeholder: '60' },
      { key: 'active', label: 'Active', type: 'toggle' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
    seedItems: [{ id: 'comp-1', name: 'Weekend Overtime Rule', expiryDays: 60, active: true, notes: 'Applicable on approved weekend work logs.' }],
  },
  onboarding: {
    storageKey: 'hrms_setting_onboarding',
    title: 'Onboarding Workflows',
    kicker: 'Employee Settings',
    description: 'Maintain onboarding checklists, responsible teams, and timeline checkpoints for new hires.',
    itemName: 'onboarding stage',
    emptyState: 'No onboarding stages configured yet.',
    primaryMetricLabel: 'Workflow stages',
    fields: [
      { key: 'name', label: 'Stage Name', type: 'text', required: true, placeholder: 'Document collection' },
      { key: 'owner', label: 'Owner', type: 'text', placeholder: 'HR Operations' },
      { key: 'timeline', label: 'Timeline (days)', type: 'number', placeholder: '2' },
      { key: 'active', label: 'Active', type: 'toggle' },
    ],
    seedItems: [{ id: 'onboard-1', name: 'Document Collection', owner: 'HR Operations', timeline: 2, active: true }],
  },
  visitManagementSettings: {
    storageKey: 'hrms_setting_visit_management',
    title: 'Visit Management Settings',
    kicker: 'Advance Settings',
    description: 'Maintain visitor access rules, approvals, and operational preferences for front-office workflows.',
    itemName: 'visit rule',
    emptyState: 'No visit management settings configured yet.',
    primaryMetricLabel: 'Visit rules',
    fields: [
      { key: 'name', label: 'Rule Name', type: 'text', required: true, placeholder: 'Visitor pre-approval' },
      { key: 'owner', label: 'Owner', type: 'text', placeholder: 'Admin Desk' },
      { key: 'active', label: 'Active', type: 'toggle' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
    seedItems: [{ id: 'visit-1', name: 'Visitor Pre-Approval', owner: 'Admin Desk', active: true, notes: 'Guests require host approval before check-in.' }],
  },
  approvalFlow: {
    storageKey: 'hrms_setting_approval_flow',
    title: 'Approval Flow Center',
    kicker: 'System Settings',
    description: 'Maintain routing logic for leave, attendance, expenses, and employee-related approvals.',
    itemName: 'approval flow',
    emptyState: 'No approval flows configured yet.',
    primaryMetricLabel: 'Approval chains',
    fields: [
      { key: 'name', label: 'Flow Name', type: 'text', required: true, placeholder: 'Leave approvals' },
      { key: 'module', label: 'Module', type: 'select', required: true, options: [{ label: 'Leave', value: 'Leave' }, { label: 'Attendance', value: 'Attendance' }, { label: 'Expense', value: 'Expense' }, { label: 'Employee', value: 'Employee' }] },
      { key: 'steps', label: 'Steps', type: 'number', required: true, placeholder: '2' },
      { key: 'active', label: 'Active', type: 'toggle' },
    ],
    seedItems: [{ id: 'approval-1', name: 'Leave Approvals', module: 'Leave', steps: 2, active: true }],
  },
  importWizard: {
    storageKey: 'hrms_setting_import_wizard',
    title: 'Import Wizard Templates',
    kicker: 'System Settings',
    description: 'Maintain import templates, file expectations, and operational notes for master-data imports.',
    itemName: 'import template',
    emptyState: 'No import templates configured yet.',
    primaryMetricLabel: 'Templates',
    fields: [
      { key: 'name', label: 'Template Name', type: 'text', required: true, placeholder: 'Employee import' },
      { key: 'module', label: 'Module', type: 'text', placeholder: 'Employees' },
      { key: 'requiredColumns', label: 'Required Columns', type: 'textarea', placeholder: 'firstName, email, roleId' },
      { key: 'active', label: 'Active', type: 'toggle' },
    ],
    seedItems: [{ id: 'import-1', name: 'Employee Import', module: 'Employees', requiredColumns: 'firstName, lastName, email, roleId', active: true }],
  },
};
