import { MenuSectionConfig } from './access.models';

export const SAAS_MENU_SECTIONS: MenuSectionConfig[] = [
  {
    id: 'self-service',
    label: 'Self Service',
    description: 'Employee facing modules',
    items: [
      {
        id: 'dashboard',
        label: 'Dashboard',
        route: '/dashboard',
        moduleSlug: 'dashboard',
        icon: 'dashboard',
        description: 'Overview, approvals, attendance pulse, and daily activity.',
        context: 'Workspace',
        accent: 'bg-indigo-500',
        quickLinkTone: 'bg-indigo-50 text-indigo-600',
        permission: 'dashboard.view',
        tab: 'selfService',
      },
      {
        id: 'profile',
        label: 'My Profile',
        route: '/profile',
        icon: 'profile',
        moduleSlug: 'profile',
        description: 'Personal details, employment info, and profile records.',
        context: 'People Ops',
        accent: 'bg-slate-500',
        quickLinkTone: 'bg-slate-100 text-slate-700',
        permission: 'profile.view',
      },

      {
        id: 'billing',
        label: 'Billing',
        route: '/billing',
        icon: 'dashboard',
        moduleSlug: 'dashboard',
        description: 'Trial status, upgrades, invoices, and workspace subscription controls.',
        context: 'Workspace',
        accent: 'bg-emerald-500',
        quickLinkTone: 'bg-emerald-50 text-emerald-700',
        permission: 'billing.view',
      },
      {
        id: 'attendance',
        label: 'Attendance',
        route: '/attendance',
        icon: 'attendance',
        moduleSlug: 'attendance',
        description: 'Punch activity, history, shifts, and attendance records.',
        context: 'Attendance',
        accent: 'bg-cyan-500',
        quickLinkTone: 'bg-cyan-50 text-cyan-600',
        lockedDescription: 'Attendance is available in your role, but not enabled for this organization.',
        permission: 'attendance.view',
        addon: 'attendance',
        tab: 'attendance',
        userInfo: [
          { key: 'shiftChangePerm', operator: 'truthy' },
        ],
      },
      {
        id: 'leaves',
        label: 'Leaves',
        route: '/leaves',
        icon: 'leave',
        moduleSlug: 'leave',
        description: 'Leave requests, balances, approvals, and holiday planning.',
        context: 'Workforce',
        accent: 'bg-emerald-500',
        quickLinkTone: 'bg-emerald-50 text-emerald-600',
        lockedDescription: 'Leave management is available in your role, but not enabled for this organization.',
        permission: 'leave.apply',
        addon: 'leave',
        tab: 'leave',
      },
      {
        id: 'payroll',
        label: 'Payroll',
        route: '/payroll',
        icon: 'payroll',
        moduleSlug: 'payroll',
        description: 'Payslips, salary visibility, and payroll summaries.',
        context: 'Workforce',
        accent: 'bg-fuchsia-500',
        quickLinkTone: 'bg-fuchsia-50 text-fuchsia-600',
        lockedDescription: 'Payroll is available in your role, but not enabled for this organization.',
        permission: 'payroll.view',
        addon: 'payroll',
        tab: 'payroll',
        userInfo: [{ key: 'paySlip', operator: 'neq', value: 0 }],
      },
      {
        id: 'timesheets',
        label: 'Timesheets',
        route: '/timesheets',
        icon: 'timesheets',
        moduleSlug: 'timesheets',
        description: 'Work logs, billable time, and daily effort tracking.',
        context: 'Productivity',
        accent: 'bg-rose-500',
        quickLinkTone: 'bg-rose-50 text-rose-600',
        lockedDescription: 'Timesheets are available in your role, but not enabled for this organization.',
        permission: 'timesheets.view',
        addon: 'timesheets',
      },
      {
        id: 'expenses',
        label: 'Expenses',
        route: '/expenses',
        icon: 'expenses',
        moduleSlug: 'expenses',
        description: 'Claims, reimbursements, and expense record tracking.',
        context: 'Workforce',
        accent: 'bg-amber-500',
        quickLinkTone: 'bg-amber-50 text-amber-700',
        lockedDescription: 'Expenses are available in your role, but not enabled for this organization.',
        permission: 'expenses.view',
        addon: 'expenses',
      },
      {
        id: 'projects',
        label: 'Projects',
        route: '/projects',
        icon: 'projects',
        moduleSlug: 'projects',
        description: 'Projects, milestones, collaboration, and delivery tracking.',
        context: 'Productivity',
        accent: 'bg-violet-500',
        quickLinkTone: 'bg-violet-50 text-violet-600',
        lockedDescription: 'Projects are available in your role, but not enabled for this organization.',
        permission: 'projects.view',
        addon: 'projects',
      },
      {
        id: 'reports',
        label: 'Reports',
        route: '/reports',
        icon: 'reports',
        moduleSlug: 'reports',
        description: 'Operational insights, exports, trends, and analytics.',
        context: 'Productivity',
        accent: 'bg-orange-500',
        quickLinkTone: 'bg-orange-50 text-orange-600',
        lockedDescription: 'Reports are available in your role, but not enabled for this organization.',
        permission: 'reports.view',
        addon: 'reports',
      },
    ],
  },
  {
    id: 'people',
    label: 'Admin & HR',
    description: 'Management and configuration modules',
    items: [
      {
        id: 'employees',
        label: 'Employees',
        route: '/employees',
        icon: 'employees',
        moduleSlug: 'employees',
        description: 'Employee directory, records, and organization structure.',
        context: 'People Ops',
        accent: 'bg-sky-500',
        quickLinkTone: 'bg-sky-50 text-sky-600',
        permission: 'employees.view',
        tab: 'employee',
      },
      {
        id: 'invitations',
        label: 'Invitations',
        route: '/employees/invitations',
        icon: 'invitations',
        moduleSlug: 'employees',
        description: 'Invite and onboard employees into the organization.',
        context: 'People Ops',
        accent: 'bg-sky-500',
        quickLinkTone: 'bg-sky-50 text-sky-700',
        permission: 'employees.invite',
        tab: 'employee',
      },
      {
        id: 'visitor-management',
        label: 'Visitor Management',
        route: '/visit-management',
        icon: 'visitors',
        moduleSlug: 'visitorManagement',
        description: 'Visitor entries, gate passes, and front desk records.',
        context: 'People Ops',
        accent: 'bg-lime-500',
        quickLinkTone: 'bg-lime-50 text-lime-700',
        lockedDescription: 'Visitor management is available in your role, but not enabled for this organization.',
        permission: 'visitorManagement.view',
        addon: 'visitorManagement',
        tab: 'admin',
      },
    ],
  },
  {
    id: 'system',
    label: 'System',
    description: 'System controls, compliance, and administration',
    items: [
      {
        id: 'team-attendance',
        label: 'Team Attendance',
        route: '/admin/team-attendance',
        icon: 'team-attendance',
        moduleSlug: 'attendance',
        description: 'Team-wide attendance visibility and daily workforce monitoring.',
        context: 'Attendance',
        accent: 'bg-cyan-500',
        quickLinkTone: 'bg-cyan-50 text-cyan-700',
        lockedDescription: 'Team attendance is available in your role, but the attendance add-on is not enabled for this organization.',
        permission: 'attendance.team.view',
        addon: 'attendance',
        tab: 'admin',
      },
      {
        id: 'regularization',
        label: 'Regularization',
        route: '/admin/regularization',
        icon: 'regularization',
        moduleSlug: 'regularization',
        description: 'Attendance correction requests and approval handling.',
        context: 'Attendance',
        accent: 'bg-amber-500',
        quickLinkTone: 'bg-amber-50 text-amber-700',
        lockedDescription: 'Regularization is available in your role, but the attendance add-on is not enabled for this organization.',
        permission: 'attendance.regularization.view',
        addon: 'attendance',
        tab: 'admin',
      },
      {
        id: 'documents',
        label: 'Documents',
        route: '/admin/documents',
        icon: 'documents',
        moduleSlug: 'documents',
        description: 'Policies, HR documents, and employee file storage.',
        context: 'People Ops',
        accent: 'bg-slate-500',
        quickLinkTone: 'bg-slate-100 text-slate-700',
        permission: 'documents.view',
        tab: 'admin',
      },
      {
        id: 'roles',
        label: 'Roles & Access',
        route: '/admin/roles',
        icon: 'roles',
        moduleSlug: 'roles',
        description: 'Role matrix, permissions, and access governance.',
        context: 'Admin Control',
        accent: 'bg-violet-500',
        quickLinkTone: 'bg-violet-50 text-violet-700',
        permission: 'roles.view',
        tab: 'admin',
      },
      {
        id: 'announcements',
        label: 'Announcements',
        route: '/admin/announcements',
        icon: 'announcements',
        moduleSlug: 'announcements',
        description: 'Publish company-wide updates and internal communication.',
        context: 'Admin Control',
        accent: 'bg-pink-500',
        quickLinkTone: 'bg-pink-50 text-pink-700',
        permission: 'announcements.view',
        tab: 'admin',
      },
      {
        id: 'settings',
        label: 'Settings',
        route: '/settings',
        icon: 'settings',
        moduleSlug: 'settings',
        description: 'Organization settings, policy setup, and configuration.',
        context: 'Admin Control',
        accent: 'bg-teal-500',
        quickLinkTone: 'bg-teal-50 text-teal-700',
        permission: 'settings.view',
        tab: 'admin',
      },
      {
        id: 'addons',
        label: 'Add-ons',
        route: '/add-ons',
        icon: 'addons',
        moduleSlug: 'settings',
        description: 'Enable modules, review locked capabilities, and manage expansion.',
        context: 'Admin Control',
        accent: 'bg-violet-500',
        quickLinkTone: 'bg-violet-50 text-violet-700',
        permission: 'addons.view',
        tab: 'admin',
      },
      {
        id: 'audit',
        label: 'Audit Logs',
        route: '/admin/audit',
        icon: 'audit',
        moduleSlug: 'audit',
        description: 'Security activity, compliance trails, and operational logs.',
        context: 'Admin Control',
        accent: 'bg-slate-500',
        quickLinkTone: 'bg-slate-100 text-slate-600',
        permission: 'audit.view',
        tab: 'admin',
      },
    ],
  },
];
