import { MenuSectionConfig } from './access.models';

export const SAAS_MENU_SECTIONS: MenuSectionConfig[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    badge: 'Role Based',
    description: 'Employee, admin, and platform dashboard entry',
    items: [
      {
        id: 'dashboard',
        label: 'Overview',
        route: '/dashboard',
        moduleSlug: 'dashboard',
        icon: 'dashboard',
        description: 'Role based workspace summary.',
        context: 'Self Service',
        accent: 'bg-indigo-500',
        quickLinkTone: 'bg-indigo-50 text-indigo-600',
        permission: 'dashboard.view',
      },
    ],
  },
  {
    id: 'self-service',
    label: 'Self Service',
    badge: 'Employee',
    description: 'Employee own data, requests, payroll, profile, and status',
    items: [
      {
        id: 'self-attendance',
        label: 'My Attendance',
        route: '/self-service/attendance',
        icon: 'attendance',
        moduleSlug: 'attendance',
        description: 'My attendance, punch actions, history, overtime, and regularization requests.',
        context: 'Self Service',
        accent: 'bg-cyan-500',
        quickLinkTone: 'bg-cyan-50 text-cyan-600',
        lockedDescription: 'Attendance is not enabled for this organization.',
        permission: 'attendance.view',
        addon: 'attendance',
        tab: 'attendance',
      },
      {
        id: 'self-attendance-qr',
        label: 'Attendance QR',
        route: '/self-service/attendance-qr',
        icon: 'attendance',
        moduleSlug: 'attendance',
        description: 'Generate your short-lived kiosk QR token for office attendance.',
        context: 'Self Service',
        accent: 'bg-cyan-500',
        quickLinkTone: 'bg-cyan-50 text-cyan-700',
        lockedDescription: 'Attendance is not enabled for this organization.',
        permission: 'attendance.view',
        addon: 'attendance',
      },
      {
        id: 'self-leave',
        label: 'Leave',
        route: '/leaves?view=request',
        icon: 'leave',
        moduleSlug: 'leave',
        description: 'Apply leave, short day leave, time off, and track leave requests.',
        context: 'Self Service',
        accent: 'bg-emerald-500',
        quickLinkTone: 'bg-emerald-50 text-emerald-600',
        lockedDescription: 'Leave is not enabled for this organization.',
        permission: 'leave.view',
        addon: 'leave',
        tab: 'leave',
      },
      {
        id: 'self-payroll',
        label: 'Payroll',
        route: '/payroll',
        icon: 'payroll',
        moduleSlug: 'payroll',
        description: 'Payslip, salary details, reimbursements, and payroll requests.',
        context: 'Self Service',
        accent: 'bg-fuchsia-500',
        quickLinkTone: 'bg-fuchsia-50 text-fuchsia-600',
        lockedDescription: 'Payroll is not enabled for this organization.',
        permission: 'payroll.view',
        addon: 'payroll',
        tab: 'payroll',
      },
      {
        id: 'self-timesheet',
        label: 'Timesheet',
        route: '/timesheets',
        icon: 'timesheets',
        moduleSlug: 'timesheets',
        description: 'My timesheets and work hour entries.',
        context: 'Self Service',
        accent: 'bg-violet-500',
        quickLinkTone: 'bg-violet-50 text-violet-600',
        permission: 'timesheets.view',
        addon: 'timesheets',
      },
      {
        id: 'self-my-approvals',
        label: 'Approval Center',
        route: '/admin/approvals',
        icon: 'regularization',
        moduleSlug: 'attendance',
        description: 'Manager approval queue for attendance, leave, expense, and workflow requests.',
        context: 'Self Service',
        accent: 'bg-amber-500',
        quickLinkTone: 'bg-amber-50 text-amber-700',
        permission: ['attendance.regularization.view', 'leaves.approve', 'regularization.view'],
      },
      {
        id: 'self-my-requests',
        label: 'My Requests',
        route: '/self-service/requests',
        icon: 'documents',
        moduleSlug: 'dashboard',
        description: 'Track my pending, approved, and rejected requests in one place.',
        context: 'Self Service',
        accent: 'bg-slate-500',
        quickLinkTone: 'bg-slate-100 text-slate-700',
        permission: 'dashboard.view',
      },
      {
        id: 'self-my-team',
        label: 'My Team',
        route: '/my-team',
        icon: 'team-attendance',
        moduleSlug: 'dashboard',
        description: 'Reporting manager, peers, and direct reportees.',
        context: 'Self Service',
        accent: 'bg-sky-500',
        quickLinkTone: 'bg-sky-50 text-sky-700',
        permission: 'dashboard.view',
      },
      {
        id: 'self-organization',
        label: 'Organization',
        route: '/settings/organisation/policies',
        icon: 'settings',
        moduleSlug: 'settings',
        description: 'Policies, circulars, correspondence, holidays, and company information.',
        context: 'Self Service',
        accent: 'bg-teal-500',
        quickLinkTone: 'bg-teal-50 text-teal-700',
        permission: ['settings.view', 'documents.view', 'announcements.view'],
      },
      {
        id: 'self-profile',
        label: 'My Profile',
        route: '/profile',
        icon: 'profile',
        moduleSlug: 'profile',
        description: 'Employment history, profile details, activity logs, and assets.',
        context: 'Self Service',
        accent: 'bg-slate-500',
        quickLinkTone: 'bg-slate-100 text-slate-700',
        permission: 'profile.view',
      },
    ],
  },
  {
    id: 'employees',
    label: 'Employees',
    badge: 'Admin',
    description: 'Employee management exactly separated from self service',
    items: [
      {
        id: 'employee-dashboard',
        label: 'Dashboard',
        route: '/employees?view=dashboard',
        icon: 'dashboard',
        moduleSlug: 'employees',
        description: 'Employee overview and people workspace.',
        context: 'Employees',
        accent: 'bg-sky-500',
        quickLinkTone: 'bg-sky-50 text-sky-600',
        permission: 'employees.view',
        tab: 'employee',
      },
      {
        id: 'employee-onboarding',
        label: 'Onboarding',
        route: '/employees/invitations',
        icon: 'invitations',
        moduleSlug: 'employees',
        description: 'Invite employees and manage onboarding.',
        context: 'Employees',
        accent: 'bg-sky-500',
        quickLinkTone: 'bg-sky-50 text-sky-700',
        permission: ['employees.invite', 'employees.view'],
        tab: 'employee',
      },
      {
        id: 'employee-on-job',
        label: 'On Job',
        route: '/employees?view=on-job',
        icon: 'employees',
        moduleSlug: 'employees',
        description: 'Active employee directory and employment records.',
        context: 'Employees',
        accent: 'bg-sky-500',
        quickLinkTone: 'bg-sky-50 text-sky-700',
        permission: 'employees.view',
        tab: 'employee',
      },
      {
        id: 'employee-lifecycle',
        label: 'Lifecycle',
        route: '/employees?view=lifecycle',
        icon: 'employees',
        moduleSlug: 'employees',
        description: 'Employee lifecycle, changes, onboarding, and offboarding.',
        context: 'Employees',
        accent: 'bg-sky-500',
        quickLinkTone: 'bg-sky-50 text-sky-700',
        permission: ['employees.view', 'employees.edit'],
        tab: 'employee',
      },
      {
        id: 'employee-reports',
        label: 'Reports',
        route: '/reports',
        icon: 'reports',
        moduleSlug: 'reports',
        description: 'Employee reports and exports.',
        context: 'Employees',
        accent: 'bg-orange-500',
        quickLinkTone: 'bg-orange-50 text-orange-600',
        permission: 'reports.view',
        addon: 'reports',
      },
    ],
  },
  {
    id: 'attendance',
    label: 'Attendance Management',
    badge: 'HR / Admin',
    description: 'Admin attendance register, corrections, policies, and reports',
    items: [
      {
        id: 'attendance-dashboard',
        label: 'Attendance Module',
        route: '/admin/attendance',
        roles: ['admin'],
        icon: 'dashboard',
        moduleSlug: 'attendance',
        description: 'Admin attendance landing page with management shortcuts.',
        context: 'Attendance Management',
        accent: 'bg-cyan-500',
        quickLinkTone: 'bg-cyan-50 text-cyan-600',
        permission: 'attendance.team.view',
        addon: 'attendance',
        tab: 'attendance',
      },
      {
        id: 'attendance-register',
        label: 'Team Attendance Register',
        route: '/admin/attendance/register',
        roles: ['admin'],
        icon: 'attendance',
        moduleSlug: 'attendance',
        description: 'All employees attendance register with filters and review actions.',
        context: 'Attendance Management',
        accent: 'bg-cyan-500',
        quickLinkTone: 'bg-cyan-50 text-cyan-600',
        permission: 'attendance.team.view',
        addon: 'attendance',
        tab: 'attendance',
      },
      {
        id: 'attendance-visits',
        label: 'Visits',
        route: '/visit-management',
        roles: ['admin'],
        icon: 'visitors',
        moduleSlug: 'visitorManagement',
        description: 'Field visits and visitor management workspace.',
        context: 'Attendance Management',
        accent: 'bg-lime-500',
        quickLinkTone: 'bg-lime-50 text-lime-700',
        permission: ['visitorManagement.view', 'attendance.team.view'],
        addon: 'visitorManagement',
      },
      {
        id: 'attendance-shift-planner',
        label: 'Shift Planner',
        route: '/admin/attendance/workspace?view=shift-planner',
        roles: ['admin'],
        icon: 'shift-planner',
        moduleSlug: 'attendance',
        description: 'Shift planning and roster controls.',
        context: 'Attendance Management',
        accent: 'bg-cyan-500',
        quickLinkTone: 'bg-cyan-50 text-cyan-700',
        permission: 'attendance.team.view',
        addon: 'attendance',
        tab: 'attendance',
      },
      {
        id: 'attendance-employee-tracking',
        label: 'Employee Tracking',
        route: '/admin/attendance/workspace?view=tracking',
        roles: ['admin'],
        icon: 'team-attendance',
        moduleSlug: 'attendance',
        description: 'Track employees and field attendance.',
        context: 'Attendance Management',
        accent: 'bg-cyan-500',
        quickLinkTone: 'bg-cyan-50 text-cyan-700',
        permission: 'attendance.team.view',
        addon: 'attendance',
        tab: 'attendance',
      },
      {
        id: 'attendance-geofence',
        label: 'Geo-fence',
        route: '/admin/attendance/geofence',
        roles: ['admin'],
        icon: 'geofence',
        moduleSlug: 'geofence',
        description: 'Geo-fence and location attendance controls.',
        context: 'Attendance Management',
        accent: 'bg-cyan-500',
        quickLinkTone: 'bg-cyan-50 text-cyan-700',
        permission: 'geofence.view',
        addon: 'attendance',
        tab: 'attendance',
      },
      {
        id: 'attendance-regularizations',
        label: 'Regularizations',
        route: '/admin/attendance/regularizations',
        roles: ['admin'],
        icon: 'regularization',
        moduleSlug: 'attendance',
        description: 'Review and process attendance correction requests.',
        context: 'Attendance Management',
        accent: 'bg-rose-500',
        quickLinkTone: 'bg-rose-50 text-rose-700',
        permission: ['regularization.view', 'attendance.regularization.view'],
        addon: 'attendance',
      },
      {
        id: 'attendance-integrations',
        label: 'Integrations',
        route: '/admin/attendance/integrations',
        roles: ['admin'],
        icon: 'settings',
        moduleSlug: 'attendance',
        description: 'Biometric, face, and attendance integrations.',
        context: 'Attendance Management',
        accent: 'bg-cyan-500',
        quickLinkTone: 'bg-cyan-50 text-cyan-700',
        permission: 'attendance.team.view',
        addon: 'attendance',
        tab: 'attendance',
      },
      {
        id: 'attendance-addons',
        label: 'Add-ons',
        route: '/add-ons',
        roles: ['admin'],
        icon: 'addons',
        moduleSlug: 'settings',
        description: 'Attendance add-ons and upgrade options.',
        context: 'Attendance',
        accent: 'bg-violet-500',
        quickLinkTone: 'bg-violet-50 text-violet-700',
        permission: ['addons.view', 'settings.view'],
      },
      {
        id: 'attendance-reports',
        label: 'Reports',
        route: '/admin/attendance/reports',
        roles: ['admin'],
        icon: 'reports',
        moduleSlug: 'reports',
        description: 'Attendance reports and analytics.',
        context: 'Attendance Management',
        accent: 'bg-orange-500',
        quickLinkTone: 'bg-orange-50 text-orange-600',
        permission: 'reports.view',
        addon: 'reports',
      },
    ],
  },
  {
    id: 'leave',
    label: 'Leave',
    badge: 'Module',
    description: 'Leave dashboard, applications, balances, short day, time off, and comp off',
    items: [
      {
        id: 'leave-dashboard',
        label: 'Dashboard',
        route: '/leaves?view=dashboard',
        icon: 'dashboard',
        moduleSlug: 'leave',
        description: 'Leave dashboard and request summary.',
        context: 'Leave',
        accent: 'bg-emerald-500',
        quickLinkTone: 'bg-emerald-50 text-emerald-600',
        permission: 'leave.view',
        addon: 'leave',
        tab: 'leave',
      },
      {
        id: 'leave-applications',
        label: 'Leave Applications',
        route: '/leaves?view=request',
        icon: 'leave',
        moduleSlug: 'leave',
        description: 'Apply and manage leave applications.',
        context: 'Leave',
        accent: 'bg-emerald-500',
        quickLinkTone: 'bg-emerald-50 text-emerald-600',
        permission: 'leave.view',
        addon: 'leave',
        tab: 'leave',
      },
      {
        id: 'leave-on-leave',
        label: 'Employee(s) On Leave',
        route: '/leaves?view=dashboard',
        icon: 'employees',
        moduleSlug: 'leave',
        description: 'See employees currently on leave.',
        context: 'Leave',
        accent: 'bg-emerald-500',
        quickLinkTone: 'bg-emerald-50 text-emerald-700',
        permission: 'leave.view',
        addon: 'leave',
        tab: 'leave',
      },
      {
        id: 'leave-balance',
        label: 'Leave Balance',
        route: '/leaves?view=dashboard',
        icon: 'reports',
        moduleSlug: 'leave',
        description: 'Current, previous, and settlement leave balances.',
        context: 'Leave',
        accent: 'bg-emerald-500',
        quickLinkTone: 'bg-emerald-50 text-emerald-700',
        permission: ['leave.balance.view', 'leave.view'],
        addon: 'leave',
        tab: 'leave',
      },
      {
        id: 'leave-short-day',
        label: 'Short Day Leave',
        route: '/settings/leave/short-day-leave',
        icon: 'leave',
        moduleSlug: 'leave',
        description: 'Short day leave configuration and requests.',
        context: 'Leave',
        accent: 'bg-emerald-500',
        quickLinkTone: 'bg-emerald-50 text-emerald-700',
        permission: ['leave.shortDay.view', 'leave.view'],
        addon: 'leave',
        tab: 'leave',
      },
      {
        id: 'leave-time-off',
        label: 'Time Off',
        route: '/settings/leave/time-off',
        icon: 'timesheets',
        moduleSlug: 'leave',
        description: 'Time off settings and requests.',
        context: 'Leave',
        accent: 'bg-emerald-500',
        quickLinkTone: 'bg-emerald-50 text-emerald-700',
        permission: ['leave.timeOff.view', 'leave.view'],
        addon: 'leave',
        tab: 'leave',
      },
      {
        id: 'leave-comp-off',
        label: 'Comp Off Balance',
        route: '/settings/leave/comp-off',
        icon: 'reports',
        moduleSlug: 'leave',
        description: 'Comp off balance and policy.',
        context: 'Leave',
        accent: 'bg-emerald-500',
        quickLinkTone: 'bg-emerald-50 text-emerald-700',
        permission: ['leave.compOff.view', 'leave.view'],
        addon: 'leave',
        tab: 'leave',
      },
    ],
  },
  {
    id: 'settings',
    label: 'Settings',
    badge: 'Admin',
    description: 'Admin settings, policies, organization setup, and controls',
    items: [
      {
        id: 'settings-home',
        label: 'All Settings',
        route: '/settings',
        icon: 'settings',
        moduleSlug: 'settings',
        description: 'All organization, employee, attendance, leave, and approval settings.',
        context: 'Settings',
        accent: 'bg-teal-500',
        quickLinkTone: 'bg-teal-50 text-teal-700',
        permission: 'settings.view',
        tab: 'admin',
      },
      {
        id: 'settings-organization',
        label: 'Organization Settings',
        route: '/settings/organisation/organisation-profile',
        icon: 'settings',
        moduleSlug: 'settings',
        description: 'Organization profile, departments, designations, grades, zones, and locations.',
        context: 'Settings',
        accent: 'bg-teal-500',
        quickLinkTone: 'bg-teal-50 text-teal-700',
        permission: 'settings.view',
        tab: 'admin',
      },
      {
        id: 'settings-attendance',
        label: 'Attendance Settings',
        route: '/settings/attendance/shift',
        icon: 'attendance',
        moduleSlug: 'settings',
        description: 'Shifts, regularization, modes, devices, weekly off, remote work, and face recognition.',
        context: 'Settings',
        accent: 'bg-cyan-500',
        quickLinkTone: 'bg-cyan-50 text-cyan-700',
        permission: 'settings.view',
        tab: 'admin',
      },
      {
        id: 'settings-leave',
        label: 'Leave Settings',
        route: '/settings/leave/leave-types',
        icon: 'leave',
        moduleSlug: 'settings',
        description: 'Leave types, short day, time off, and comp off settings.',
        context: 'Settings',
        accent: 'bg-emerald-500',
        quickLinkTone: 'bg-emerald-50 text-emerald-700',
        permission: 'settings.view',
        tab: 'admin',
      },
      {
        id: 'settings-employee',
        label: 'Employee Settings',
        route: '/settings/employee/onboarding',
        icon: 'employees',
        moduleSlug: 'settings',
        description: 'Onboarding and employee setup controls.',
        context: 'Settings',
        accent: 'bg-sky-500',
        quickLinkTone: 'bg-sky-50 text-sky-700',
        permission: 'settings.view',
        tab: 'admin',
      },
      {
        id: 'settings-approval-flow',
        label: 'Approval Flow',
        route: '/settings/approval-flow',
        icon: 'regularization',
        moduleSlug: 'settings',
        description: 'Approval workflow and request routing.',
        context: 'Settings',
        accent: 'bg-amber-500',
        quickLinkTone: 'bg-amber-50 text-amber-700',
        permission: 'settings.view',
        tab: 'admin',
      },
      {
        id: 'settings-import-wizard',
        label: 'Import Wizard',
        route: '/settings/import-wizard',
        icon: 'documents',
        moduleSlug: 'settings',
        description: 'Bulk import setup and data tools.',
        context: 'Settings',
        accent: 'bg-slate-500',
        quickLinkTone: 'bg-slate-100 text-slate-700',
        permission: 'settings.view',
        tab: 'admin',
      },
    ],
  },
  {
    id: 'addons',
    label: 'Add-ons',
    badge: 'Modules',
    description: 'Module launcher and purchasable add-ons',
    items: [
      {
        id: 'addons-hub',
        label: 'Add-ons Hub',
        route: '/add-ons',
        icon: 'addons',
        moduleSlug: 'settings',
        description: 'Open active modules and upgrade locked modules.',
        context: 'Add-ons',
        accent: 'bg-violet-500',
        quickLinkTone: 'bg-violet-50 text-violet-700',
        permission: ['addons.view', 'settings.view'],
      },
      {
        id: 'addons-billing',
        label: 'Subscription & Plan',
        route: '/billing',
        icon: 'payroll',
        moduleSlug: 'dashboard',
        description: 'Plans, seat based billing, add-ons, and upgrades.',
        context: 'Add-ons',
        accent: 'bg-emerald-500',
        quickLinkTone: 'bg-emerald-50 text-emerald-700',
        permission: ['billing.view', 'addons.view'],
      },
    ],
  },
  {
    id: 'visitormanagement',
    label: 'Visitor Management',
    badge: 'Add-on',
    description: 'Visitor dashboard and active visitor operations',
    items: [
      {
        id: 'visitor-dashboard',
        label: 'Dashboard',
        route: '/visit-management',
        icon: 'dashboard',
        moduleSlug: 'visitorManagement',
        description: 'Visitor management dashboard.',
        context: 'Visitor Management',
        accent: 'bg-lime-500',
        quickLinkTone: 'bg-lime-50 text-lime-700',
        lockedDescription: 'Visitor management is not enabled for this organization.',
        permission: 'visitorManagement.view',
        addon: 'visitorManagement',
      },
      {
        id: 'active-visitors',
        label: 'Active Visitors',
        route: '/visit-management',
        icon: 'visitors',
        moduleSlug: 'visitorManagement',
        description: 'Active visitors, entries, and front desk actions.',
        context: 'Visitor Management',
        accent: 'bg-lime-500',
        quickLinkTone: 'bg-lime-50 text-lime-700',
        lockedDescription: 'Visitor management is not enabled for this organization.',
        permission: 'visitorManagement.view',
        addon: 'visitorManagement',
      },
    ],
  },
  {
    id: 'organization',
    label: 'Organization',
    badge: 'Platform',
    description: 'Tenant, module, subscription, and usage management',
    items: [
      {
        id: 'platform-organizations',
        label: 'Organizations',
        route: '/platform?view=organizations',
        icon: 'settings',
        moduleSlug: 'settings',
        description: 'Organization profile and multi-tenant controls.',
        context: 'Organization',
        accent: 'bg-teal-500',
        quickLinkTone: 'bg-teal-50 text-teal-700',
        permission: 'settings.view',
        tab: 'admin',
      },
      {
        id: 'platform-modules',
        label: 'Module Management',
        route: '/platform?view=modules',
        icon: 'addons',
        moduleSlug: 'settings',
        description: 'Enable or disable modules for the organization.',
        context: 'Organization',
        accent: 'bg-violet-500',
        quickLinkTone: 'bg-violet-50 text-violet-700',
        permission: ['addons.view', 'settings.view'],
        tab: 'admin',
      },
      {
        id: 'platform-subscriptions',
        label: 'Subscription & Plan',
        route: '/platform?view=subscriptions',
        icon: 'payroll',
        moduleSlug: 'dashboard',
        description: 'Subscription, plan, revenue, and billing overview.',
        context: 'Organization',
        accent: 'bg-emerald-500',
        quickLinkTone: 'bg-emerald-50 text-emerald-700',
        permission: ['billing.view', 'addons.view'],
      },
      {
        id: 'platform-analytics',
        label: 'Usage & Analytics',
        route: '/platform?view=analytics',
        icon: 'reports',
        moduleSlug: 'reports',
        description: 'Usage analytics and platform reports.',
        context: 'Organization',
        accent: 'bg-orange-500',
        quickLinkTone: 'bg-orange-50 text-orange-600',
        permission: 'reports.view',
        addon: 'reports',
      },
    ],
  },
  {
    id: 'kiosk-management',
    label: 'Kiosk Management',
    badge: 'Attendance',
    description: 'Shared device attendance kiosks, approvals, logs, and face profile review',
    items: [
      {
        id: 'kiosk-list',
        label: 'Kiosk Devices',
        route: '/admin/kiosks',
        icon: 'settings',
        moduleSlug: 'attendance',
        description: 'Manage registered kiosk devices and activation tokens.',
        context: 'Kiosk',
        accent: 'bg-sky-500',
        quickLinkTone: 'bg-sky-50 text-sky-700',
        permission: 'attendance.team.view',
        addon: 'attendance',
        tab: 'admin',
      },
      {
        id: 'kiosk-approvals',
        label: 'Kiosk Approvals',
        route: '/admin/kiosks/approvals',
        icon: 'audit',
        moduleSlug: 'attendance',
        description: 'Approve shared attendance devices and issue kiosk tokens.',
        context: 'Kiosk',
        accent: 'bg-emerald-500',
        quickLinkTone: 'bg-emerald-50 text-emerald-700',
        permission: 'attendance.team.view',
        addon: 'attendance',
        tab: 'admin',
      },
      {
        id: 'kiosk-logs',
        label: 'Kiosk Logs',
        route: '/admin/kiosks/logs',
        icon: 'reports',
        moduleSlug: 'attendance',
        description: 'Review kiosk attendance attempts, failures, and suspicious activity.',
        context: 'Kiosk',
        accent: 'bg-orange-500',
        quickLinkTone: 'bg-orange-50 text-orange-700',
        permission: 'attendance.team.view',
        addon: 'attendance',
        tab: 'admin',
      },
      {
        id: 'kiosk-face-profiles',
        label: 'Face Profile Approvals',
        route: '/admin/kiosks/face-profiles',
        icon: 'employees',
        moduleSlug: 'attendance',
        description: 'Approve or reject employee face profile registrations for kiosk attendance.',
        context: 'Kiosk',
        accent: 'bg-violet-500',
        quickLinkTone: 'bg-violet-50 text-violet-700',
        permission: 'attendance.team.view',
        addon: 'attendance',
        tab: 'admin',
      },
      {
        id: 'kiosk-pins',
        label: 'Kiosk PINs',
        route: '/admin/kiosks/pins',
        icon: 'roles',
        moduleSlug: 'attendance',
        description: 'Set or reset employee kiosk PINs for shared-device attendance.',
        context: 'Kiosk',
        accent: 'bg-indigo-500',
        quickLinkTone: 'bg-indigo-50 text-indigo-700',
        permission: 'attendance.team.view',
        addon: 'attendance',
        tab: 'admin',
      },
      {
        id: 'kiosk-settings',
        label: 'Kiosk Settings',
        route: '/admin/kiosks/settings',
        icon: 'settings',
        moduleSlug: 'attendance',
        description: 'Review rollout checklist, device policy, and kiosk operating guidance.',
        context: 'Kiosk',
        accent: 'bg-slate-500',
        quickLinkTone: 'bg-slate-100 text-slate-700',
        permission: 'attendance.team.view',
        addon: 'attendance',
        tab: 'admin',
      },
    ],
  },
  {
    id: 'roles-permissions',
    label: 'Roles & Permissions',
    badge: 'RBAC',
    description: 'Role based access control and permission audit',
    items: [
      {
        id: 'roles',
        label: 'Roles & Access',
        route: '/admin/roles',
        icon: 'roles',
        moduleSlug: 'roles',
        description: 'Create roles and map permissions.',
        context: 'RBAC',
        accent: 'bg-violet-500',
        quickLinkTone: 'bg-violet-50 text-violet-700',
        permission: 'roles.view',
        tab: 'admin',
      },
      {
        id: 'access-audit',
        label: 'Permission Audit',
        route: '/admin/audit',
        icon: 'audit',
        moduleSlug: 'audit',
        description: 'Review access activity and audit logs.',
        context: 'RBAC',
        accent: 'bg-slate-500',
        quickLinkTone: 'bg-slate-100 text-slate-600',
        permission: 'audit.view',
        tab: 'admin',
      },
    ],
  },
];
